### ISSUE TITLE
You could have used CatBoost on GPU using Google Colab

### ISSUE THREAD

**Issue by satkatai** [rajat5ranjan/AV-LTFS-Data-Science-FinHack-ML-Hackathon#2]
Even though I have not used this approach, I read [some other's code](https://github.com/sk48880/LTFS-Data-Science-Finhack---Anlytics-Vidhya/blob/master/Loan_Default_Prediction_EDA_%26_Gradient_Boosting.ipynb) where you can pass parameter tast_type="GPU" in CatBoostClassifier to enable GPU Training.  Google Colab provides free GPU upto 12 hours without interruption.

**Comment by rajat5ranjan** [comment]
Yes true, but i had my reasons

- I was having parallel notebooks executing in my local
- There were issues with my internet connection, it was fluctuating, so didnt use Colab or Kaggle kernels.

But Thanks for the  suggestions will keep in mind next time

**Comment by rajat5ranjan** [comment]
Hence closing the issue,.
