### ISSUE TITLE
Question regarding resampling the dataset

### ISSUE THREAD

**Issue by mdalvi** [rajat5ranjan/AV-LTFS-Data-Science-FinHack-ML-Hackathon#3]
Hello rajat5rajan,

Good to see the CatBoostClassifier in action! Congrats on the achievements.

I was going through your implementation and recognized you had not undersampled/oversampled the dataset. I can see the stratified splits but no resampling!

Any thoughts on the same?

**Comment by rajat5ranjan** [comment]
Hey mdalvi,

Nice question, i was actually trying to incorporate sampling techniques, but due to the fact that i was going for a full fledged 20 splits, which holds all the data, i didn't find the need to re sample the data, so as to keep the raw data intact with all its randomness.

Thanks
